### PR TITLE
Allow using local mapnik installation for building

### PR DESCRIPTION
**Pull request by Algunenano**
Changes to allow building against a local installation of mapnik by using `make release_base` or `make debug_base`; it requires  `mapnik-config` to be in the PATH.

The default build is still using mason (downloads mason and its dependencies and sets the PATH to use it).  I'm not completely sure if the changes in postinstall are correct, though. I've tested this only on LInux, with these changes on top of v3.6.2 and mapnik 3.0.15 (with a cherry-pick for icu-59)

It should cover https://github.com/mapnik/node-mapnik/issues/784

### CODE REVIEW

**Comment by springmeyer** [comment]
Great work on this @Algunenano - this looks great. Could you also add docs to the main `README.md`?

**Comment by Algunenano** [comment]
Done. I've also modified the pre-build check (mapnik-config in PATH) to fail in the Makefile instead of failing randomly in the build process.
Please let me know if you need anything else.

**Comment by springmeyer** [comment]
Realized one more problem. The `postinstall.sh` currently pulls from the values of `--proj-lib`, `--gdal-data`, and `--icu-data`. However these are currently broken for mapnik core. Fix incoming in https://github.com/mapnik/mapnik/pull/3759. Until then the right approach here is to not set these values at all (they the defaults will be used for those libraries rather than overriding the environment variables at https://github.com/mapnik/node-mapnik/blob/dd3dc93b035742cb20061a52599a71a37b68e614/lib/mapnik.js#L17

**Comment by springmeyer** [comment]
Touched up your work and landed in #803. Thanks so much for the help on this! Been planning on fixing this myself for ages (#784) but just did not have the time. Thanks again.

**Pull request closed without merging**
