### PR TITLE
[WIP] update documentation for 2.0 specification

### PR DESCRIPTION
**Pull request by mapsam**
**Not ready, do not merge!**

This updates the JSDoc documentation in `mapnik_vector_tile.cpp` and other related files that have been significantly changed for the `2.0` specification.

Tasks:

- [x] update `mapnik_vector_tile.cpp` JSDocs
- [x] update `mapnik_image.cpp` JSDocs
- [x] ~~update `mapnik_map.cpp` JSDocs~~
- [x] JSDocs general tasks
  - [x] update all `.vector.pbf` to `.mvt` in `@examples`
  - [x] complete `DOCS TODO` questions (used as placeholders for gaps in my knowledge)
  - [x] clean up examples throughout so they match in style & language
     - [x] `assert` -> `console.log`
- [x] ~~update styles to match mapnik.org (not critical, but could use some love)~~
- [x] build `documentation/` directory
- [ ] find a new home for `/docs`

### CODE REVIEW

**Comment by mapsam** [comment]
Is there a reason a number of methods are not documented in `mapnik_map.cpp`? I'm seeing these methods in tests but not JSDoc-ready:

- [ ] [`loadFonts`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L413)
- [ ] [`memoryFonts`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L419)
- [ ] [`registerFonts`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L432)
- [ ] [`queryMapPoint`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L566)
- [ ] [`queryPoint`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L572
- [ ] [`save`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L1367)
- [ ] [`to_string`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L1382)
- [ ] [`zoomAll`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L1390)
- [ ] [`zoomToBox`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L1405)
- [ ] [`render`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L1547)
- [ ] [`renderFile`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L2216)
- [ ] [`renderSync`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L2433)
- [ ] [`renderFileSync`](https://github.com/mapnik/node-mapnik/blob/238035eae44f2d95c63efd05822a86edc8096ef8/src/mapnik_map.cpp#L2544)

cc/ @flippmoke @springmeyer

**Comment by springmeyer** [comment]
> Is there a reason a number of methods are not documented in mapnik_map.cpp

No good reason. In terms of usage of node-mapnik, the `mapnik.VectorTile` and `mapnik.Image` APIs are the most critical for good docs but `mapnik.Map` is a close follow.

**Comment by springmeyer** [comment]
@mapsam - also you may have seen https://github.com/mapnik/node-mapnik/tree/master/docs? These are an abandoned and incomplete effort at docs. They can be deleted once API docs are complete / any doc fragments in those markdown files are confirmed to be in the code. For example https://github.com/mapnik/node-mapnik/blob/master/docs/Using-Fonts.md should be ported to be in the new doc format (this proceeded the use of documentation.js). It is more narrative style so can we lean on you to figure out where this should best live?

**Comment by mapsam** [comment]
Thanks for pointing that out @springmeyer. I noticed them, but didn't realize how in depth they go. There is a wealth of knowledge in those files and we wouldn't want to lose any. I'll work on putting the necessary bits into `/documentation` and find a new home.

**Comment by mapsam** [comment]
Phew, `mapnik_image.cpp` is complete! Going to focus on getting this all rendered in a nicer format for pushing to mapnik.org before working on `mapnik_map.cpp`

**Comment by mapsam** [comment]
In favor of timeliness, I'm moving a couple of tasks out of this PR since they are mostly of out scope.

Future doc updates, including updated styles and upgraded documentationjs `4.0.0-beta` version are now ticketed in #599

All verbiage from the outdated `/docs` directory has been incorporated into `/documentation` via JSDocs **except** for [`using_fonts.md`](https://github.com/mapnik/node-mapnik/blob/master/docs/Using-Fonts.md) which has a bit of information regarding XML styles that fall outside of the API documentation scope. Maybe it would be best to move this to a wiki page for now?

### Next steps?

* :eyes: and :+1: from @springmeyer @artemp @flippmoke @BergWerkGIS to make sure things look good here
* make a PR into `gh-pages` with update `/documentation` directory

**Comment by mapsam** [comment]
Worth noting this is what documentation looks like now:

screen shot 2016-02-19 at 4 50 34 pm

**Comment by springmeyer** [comment]
Awesome @mapsam - Let's get eyes on this first thing Monday and then we'll merge.

**Pull request merged**
