### PR TITLE
Shape-Index and Mapnik-Index path variables

### PR DESCRIPTION
**Pull request by flippmoke**
Added the path variables to `mapnik_settings.js` creation. I was unsure if `gen_settings.py` also needed to be changed as well.

/cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
Looks great, thanks for moving on this @flippmoke.

Good question on`gen_settings.py`. It will be used in the case someone does a source install without mason.  I can see leaving these undefined, since in that case someone should be falling back to depending on the tools being on their PATH. Or `gen_settings.py` could embed just the name of the tool without a full path. My first instinct is the former.

**Comment by springmeyer** [comment]
realizing that maybe windows is broken from my previous changes. I can't see how `mapnik-index.js` is working since the programs appear copied into the root `/binding` directory and not `/binding/bin/`: https://github.com/mapnik/node-mapnik/blob/c24b5dd5252ac69c23148d545b4cfebb10a49862/scripts/build_against_sdk_02-copy-deps-to-bindingdir.ps1#L9-L10

/cc @flippmoke - can you tell why this is not failing on windows? Are we missing a test?

**Comment by flippmoke** [comment]
@springmeyer I had to update for another test see https://github.com/mapnik/node-mapnik/pull/748/commits/c24b5dd5252ac69c23148d545b4cfebb10a49862

**Comment by springmeyer** [comment]
per voice with @flippmoke we suspect something is still not totally right on windows. I will followup with @BergWerkGIS over at #749

**Pull request merged**
