### PR TITLE
Update mapnik version to a0ea7db1a in install_deps.sh

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by artemp** [comment]
@jseppi - I fixed mason-version in https://github.com/mapnik/node-mapnik/pull/928/commits/77b67c93562f6d3a0ec065ed59981bb52a09385f but some travis builds are still failing https://travis-ci.org/mapnik/node-mapnik/builds/571710742

```
/Users/travis/build/mapnik/node-mapnik/node_modules/node-pre-gyp/node_modules/rimraf/rimraf.js:7

let glob = undefined

^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/travis/build/mapnik/node-mapnik/node_modules/node-pre-gyp/lib/util/napi.js:4:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
``` 

/cc @springmeyer something has happened on travis ^ any ideas?

**Comment by springmeyer** [comment]
@artemp I've not seen that before. Looks perhaps related to some upstream change that broke node v4. If I'm seeing this right it means that its probably a good time to drop node v4 support, which would require bumping at least the node-mapnik minor version.

**Comment by jseppi** [comment]
@springmeyer @artemp I reran the failed test runs and they all passed! Definitely still a mystery as to why they failed to begin with.

**Comment by springmeyer** [comment]
Okay @jseppi - so I guess this is ready to merge then. BTW are you following https://github.com/mapnik/node-mapnik/blob/master/CONTRIBUTING.md#releasing? I notice there are some things out of date in that (e.g. we don't support windows anymore and we use `mason` instead of `mapnik-packaging`). I think you are generally at step 7.

**Pull request merged**
