### PR TITLE
[v3.0.x] Fix behavior of svg parsing

### PR DESCRIPTION
**Pull request by springmeyer**
- Adds new option to control whether we throw on unhandled elements
 - Ensures the default for strict mode is always false

TODO:

 - [x] ~~`throw_on_unhandled_elements` is a sort of horrible option name (so long) - can we think of something nicer?~~
 - [x] publish dev binaries - test downstream to make sure this is the right behavior
 - [x] need more test coverage?
 - [x] port this to `master` branch as well (#879)

### CODE REVIEW

**Comment by mapsam** [comment]
Tried to publish, but we have some borked publishing tokens since #874 only made it into the 4.x(master) branch. Removing tokens here should do the trick as well, since we're building on the same travis environment settings.

**Comment by springmeyer** [comment]
> mapnik@3.7.3-svg1 has been published as a dev tag

Thanks @mapsam

**Comment by springmeyer** [comment]
I'm working on finishing this branch. I've dropped the `throw_on_unhandled_elements` option and stuck with fixing the behavior of `strict` (and adding docs) in https://github.com/mapnik/node-mapnik/commit/540f5b5a51eb8e2a23a90987f66fccc49fc999d0. Assigning @mapsam for a quick review - just looking for a gut check.

**Comment by springmeyer** [comment]
Merging: travis failures are unrelated network failures - otherwise its 🍏

**Pull request merged**
