### PR TITLE
N-API port 

### PR DESCRIPTION
**Pull request by artemp**
* Port to using `N-API (node-addon-api)` 
* Split source files (based on original https://github.com/mapnik/node-mapnik/pull/812)

### CODE REVIEW

**Comment by Algunenano** [comment]
Hi @artemp, are you doing this by hand or are you using some kind of [tool](https://github.com/nodejs/node-addon-api/tree/master/tools)

**Comment by artemp** [comment]
> Hi @artemp, are you doing this by hand or are you using some kind of [tool](https://github.com/nodejs/node-addon-api/tree/master/tools)?

Both but mostly manually.
First I ran 
``` 
./node_modules/node-addon-api/tools/conversion.js src/
```
but the tool is not very clever and here are lots of inconsistent usage (pre NAN etc) added over time so I'm manually reviewing and fixing things. 
Your feedback is appreciated! 

/cc @Algunenano

**Comment by Algunenano** [comment]
Makes sense. For now I'm only done an overview of the changes, trying to familiarize myself with n-api more than reviewing the changes themselves.

One question that I have, but that is outside of the scope of the PR, is what changes are needed in the deployment of pre-compiled binaries since now I'd expect a single `.node` per platform. But that comes after making things work with n-api.

**Comment by artemp** [comment]
>  single `.node` per platform. But that comes after making things work with n-api.

That's the goal ^ :+1:

**Pull request merged**
