### PR TITLE
Split mapnik_image.cpp

### PR DESCRIPTION
**Pull request by talaj**
As per https://github.com/mapnik/node-mapnik/pull/806#issuecomment-328665183, this splits `mapnik_image.cpp` into these files:

```
src/mapnik_image.cpp
src/mapnik_image_clear.cpp
src/mapnik_image_composite.cpp
src/mapnik_image_copy.cpp
src/mapnik_image_encode.cpp
src/mapnik_image_fill.cpp
src/mapnik_image_filter.cpp
src/mapnik_image_from_buffer.cpp
src/mapnik_image_from_bytes.cpp
src/mapnik_image_open.cpp
src/mapnik_image_premultiply.cpp
src/mapnik_image_resize.cpp
src/mapnik_image_save.cpp
src/mapnik_image_solid.cpp
src/mapnik_image_svg.cpp
```

`mapnik_vector_tile.cpp` will follow in a separate pull request.

### CODE REVIEW

**Comment by flippmoke** [comment]
I think this is a great PR and was planning on merging if we resolve the merge conflicts.

**Comment by springmeyer** [comment]
Anyone have bandwidth to resolve the conflicts and get this merged?

**Comment by artemp** [comment]
@talaj - you original idea lives on in N-API port https://github.com/mapnik/node-mapnik/pull/946, thanks! 
/cc @springmeyer

**Comment by springmeyer** [comment]
#946 landed in master now as v4.5.1

**Pull request closed without merging**
