### PR TITLE
isolate changes unrelated to mapnik 3.1 from #805

### PR DESCRIPTION
**Pull request by springmeyer**
The changes in #805 were difficult to read since there were so many formatting changes and node v8 deprecation fixes mixed with mapnik 3.1 changes. So I've ported to a standalone branch here, to test, merge, and then rebase into #805. The goal is to reduce the noise in that branch to help me better review changes related to mapnik 3.1.

### CODE REVIEW

**Comment by artemp** [comment]
@springmeyer - most formatting changes I see are removing an extra space character at the end of statements. This indicates to me some inferior to emacs/vim text editors being used. As far as `clang-tidy` goes, last time I tried it was re-arranging `#include` directives and failing to understand quite a bit of c++11/14  syntax which rendered it unusable. Having said that I do use in emacs sometimes by applying to selected code regions.

**Comment by springmeyer** [comment]
Let's reboot our efforts to use clang-format and clang-tidy. Ideally we can format the entire codebase using these soon so that your emacs settings will not make any changes. Until then please try to have your PRs to node-mapnik include only substantive changes. If you have formatting changes, please commit them first to master, before creating a PR.

**Comment by talaj** [comment]
> Ideally we can format the entire codebase using these soon

Could be some large cpp files split as part of this? [/src/mapnik_vector_tile.cpp](https://github.com/mapnik/node-mapnik/blob/d9c9b5971fc3dc3eaa48cd9b3b2e001f11f66823/src/mapnik_vector_tile.cpp) has over 6000 lines, [/src/mapnik_image.cpp](https://github.com/mapnik/node-mapnik/blob/d9c9b5971fc3dc3eaa48cd9b3b2e001f11f66823/src/mapnik_image.cpp) over 4000 lines.

**Comment by springmeyer** [comment]
👍  @talaj - only reason this has not already been done is lack of motivation. If you want to do some refactoring, please feel free. Ideally we could do this before #805 merges (and as part of https://github.com/mapnik/node-mapnik/issues/807) and then rebase #805 on top of the cleanups. The reason I think this would be ideal is that to support both c++11 and c++14 for a time I'm proposing maintaining two branches: https://github.com/mapnik/node-mapnik/issues/808

**Pull request merged**
