### PR TITLE
auto build docs

### PR DESCRIPTION
**Pull request by mapsam**
Send a request to mapnik/documentation `master` branch to rebuild on travis-ci, which builds the docs and pushes to the `gh-pages` branch.

refs: #599 

TODO

- [x] land on a commit code for publishing docs - currently set to: `[publish docs]`
- [x] only run this on `master` branch builds? - currently the documentation repo itself is just [using the `master` branch to generate docs](https://github.com/mapnik/documentation/blob/gh-pages/package.json#L13) anyways, so it would be useless to run this command for any other branch.

cc @springmeyer

### CODE REVIEW

**Comment by mapsam** [comment]
Currently unable to actually get this CURL to trigger anything from the command line. Travis responds, though!

```
{
  "@type": "pending",
  "remaining_requests": 10,
  "repository": {
    "@type": "repository",
    "@href": "/repo/8884379",
    "@representation": "minimal",
    "id": 8884379,
    "name": "documentation",
    "slug": "mapnik/documentation"
  },
  "request": {
    "repository": {
      "id": 60119461,
      "owner_name": "mapnik",
      "name": "documentation"
    },
    "user": {
      "id": 40531
    },
    "message": null,
    "branch": "master",
    "config": {
    }
  },
  "resource_type": "request"
}
```

**Comment by mapsam** [comment]
This is ready to rock thanks to some 👀 from @springmeyer. Once this PR is merged:

- [ ] update the `gh-pages` branch in this repo to forward to the new documentation URL
- [ ] update URL in repo
- [ ] confirm docs are updating with some updates to `src/mapnik_map.cpp`
- [ ] over time, just remove the `gh-pages` branch.

**Comment by mapsam** [comment]
All 🍏 on travis. @BergWerkGIS okay to merge this with appveyor failing? Shouldn't have an effect on the windows builds at all.

**Comment by BergWerkGIS** [comment]
I think we are good to merge.

AppVeyor is failing because it tries to pull down [`mapnik-win-sdk-v3.0.11-163-g00e5d00-x64-14.0.7z`](https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1478/job/fpdxlmjuwuw0lc6w#L7) which we do not have.

We have [`MAPNIK_GIT: v3.0.10` defined in appveyor.yml](https://github.com/mapnik/node-mapnik/blob/5de529fe4c051c6ab6ebf8437743fffe41b353e5/appveyor.yml#L2).

Will investigate where `v3.0.11-163-g00e5d00` is coming from ...

**Comment by BergWerkGIS** [comment]
ah, found it: https://github.com/mapnik/node-mapnik/commit/3dba76ac94ae5843f5a335ad8186bef10fc46419

**Pull request merged**
