### PR TITLE
Upgrade to Nan 2.0

### PR DESCRIPTION
**Pull request by springmeyer**
Started this in order to be ready to support io.js 3.0.0. It turned out to require a major overhaul so I pushed through using a combination of https://github.com/nodejs/nan/issues/376#issuecomment-120838432 and a lot of manual fixes.

Thinking about merging this fairly soon because otherwise other pull requests are going to have to be remade a lot over time.

Still needs, before merging:

- [x] confirm travis/appveyor passing
- [x] remove now uneeded handlescopes (based on https://github.com/Level/leveldown/pull/195)
- [x] convert all Handle -> Local (based on https://github.com/Level/leveldown/pull/195) 
- [ ] add buffer requirement for constructing palettes to changelog
- [ ] try using the zero copy `Nan::NewBuffer` interface where possible (transfers ownership of `char*`)

### CODE REVIEW

**Comment by springmeyer** [comment]
plan on this: rebase once #505 is landed.

**Comment by ChALkeR** [comment]
https://github.com/nodejs/node/issues/2798

**Comment by springmeyer** [comment]
Working on finishing this. Ran into #527 and #528 while trying to get to 100% coverage which is the last problem with the branch.

**Comment by springmeyer** [comment]
Now 100% on this branch again (https://coveralls.io/builds/3694404). Will merge once travis is green.

**Comment by springmeyer** [comment]
followup: https://github.com/mapnik/node-mapnik/issues/531

**Pull request merged**
