### PR TITLE
Add mapnik-shapeindex script

### LINKED ISSUE #378: Add package.json "bin" scripts for shapeindex, nik2img
As a convenience what if there were executable scripts like `bin/mapnik-shapeindex.js` functions that looked like: https://gist.github.com/rclark/f83262655df797442e95?

This helps the end-user utilize the executable without tracking it down in the file system. Also means that a library that depends on node-mapnik could call the executable via `node_modules/.bin/mapnik-shapeindex`.

What do you think @springmeyer?

### PR DESCRIPTION
**Pull request by rclark**
Fixes #378, but only a `shapeindex` script. `nik2img` remains "hidden".

cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
travis failures are unrelated, so go ahead and merge. I'll fix the hanging `bench/error/test_vt_abort.js` shortly.

**Comment by rclark** [comment]
Appveyor unrelated too? It did seem to be *actually* failing the test there?

**Comment by springmeyer** [comment]
Good catch, yes https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.115/job/uwxwug6o7os7gxk2#L2600 needs to be working.

**Comment by rclark** [comment]
@springmeyer these test outputs make me wonder if `shapeindex` works on windows? 

The tests copy files into a temporary directory, then run the `bin/mapnik-shapeindex.js` against them via `child_process.exec`. After that returns, I had it `console.log` stdout, stderr, and the list of files in the temporary directory. Nothing on stdout or stderr, no `.index` file written to the temp dir.

```
  bin/mapnik-shapefile.js
 
 
world_merc.dbf
world_merc.prj
world_merc.shp
world_merc.shx
```

**Comment by springmeyer** [comment]
@rclark good hunch. I'll boot a windows VM next and take a closer look.

**Comment by rclark** [comment]
While you're over on the windows side... I tried installing node-mapnik on a windows machine and node-pre-gyp failed with a 403 from S3.

**Comment by springmeyer** [comment]
It looks like shapeindex works fine on windows, at least if I call it directly: https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.134/job/d6c49j8jxd7tka2w#L2240. So, I'm still baffled as to what is wrong. Sure its something simple that I'll see when I can debug locally

> While you're over on the windows side... I tried installing node-mapnik on a windows machine and node-pre-gyp failed with a 403 from S3.

Make sure you are not running node v0.10.34 (that release that broke http with aws).

**Comment by rclark** [comment]
Switched to node@0.10.36, and now failed to install mapnik with [this error message](https://gist.github.com/rclark/a431754bb746f1cf3063). I had installed an x86 c++ redistributable from here: http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by rclark** [comment]
In the meantime, changing the test script to run a command like `node C:\...\...\mapbox-shapeindex.js ...` led to successful runs on node 0.11, but the 0.10 runs still failed.

My takeaway from battling this afternoon is that child_process is not reliable across platforms.

**Comment by rclark** [comment]
I got this to pass appveyor but I'm not pleased. Basically I just avoided making child_process calls during tests by moving *most* of the logic into a node.js function at `require('mapnik').shapeindex()`.

I don't really think this is the right way to go but I'm running out of ideas.

**Comment by mojodna** [comment]
npm can be used to distribute anything, right? That makes me think that you
might be able to not wrap the binaries in JS, declare them as binaries in
package.json, and have it just work.

**Comment by rclark** [comment]
> declare them as binaries in package.json, and have it just work.

Would be perfect, except that the path to the `shapeindex` binary is going to be different depending on the platform/arch you're running with after node-pre-gyp brings in the pre-compiled mapnik binaries.

**Comment by mojodna** [comment]
Ah, right. Hmm. Symlinks to a common location after node-pre-gyp runs?

(FWIW, this is a great idea amass already know that I'd make use of it)

>

**Comment by rclark** [comment]
Got it!

:tiger: 
:shirt:
:jeans:

**Comment by springmeyer** [comment]
Yesssssss @rclark. I see travis fails were a network blip so go ahead and merge this!

**Pull request merged**
