### PR TITLE
[WIP] Port to support Mapnik master (3.1)

### PR DESCRIPTION
**Pull request by springmeyer**
A branch of node-mapnik that works against mapnik master (future 3.1)

### CODE REVIEW

**Comment by springmeyer** [comment]
@artemp I've reviewed this branch. I'm seeing several issues:

1. This test that parses invalid json should throw but now does not. It was recently fixed to throw in 3.0.x (https://github.com/mapnik/node-mapnik/pull/729)

2. rendering a vector tile to a png with a negative buffer no longer clips the white polygons. Also if you look closely the centroids for each country (small black points) are also no longer correct.

expected:



this branch:



See the fixture change I had to make to get this test passing at https://github.com/mapnik/node-mapnik/commit/7d4799763e766bd25346789b649c4cd8bbe7e3da. Now that I realize this is incorrect, I've reverted in 2b40155.

I spent some time trying to figure this out (why the image result is different) and came up short. I did not see any changes in node-mapnik or mapnik-vt that could explain it. So I suspect Mapnik core. I did try reverting @talaj's https://github.com/mapnik/mapnik/pull/347. That seemed to fix the centroids but not the polygon clipping. This is an image generated from https://github.com/mapnik/mapnik/tree/revert-347:

tile0-c actual

Heads up as well about https://github.com/mapnik/node-mapnik/issues/801#issuecomment-328354368. Not clear to me if the hit_test changes are implicated however.

**Comment by talaj** [comment]
I can reproduce the problem with negative buffer size so I will try to figure out what's wrong.

**Comment by springmeyer** [comment]
> I can reproduce the problem with negative buffer size so I will try to figure out what's wrong.

Thank you @talaj

**Comment by talaj** [comment]
Both the missing centroids and clipping should be fixed by https://github.com/mapnik/mapnik/pull/3764.

**Comment by springmeyer** [comment]
> Both the missing centroids and clipping should be fixed by mapnik/mapnik#3764.

Excellent, thank you @talaj - @artemp will be testing this more tomorrow. I will let him confirm.

**Comment by springmeyer** [comment]
Noticing this branch is close to working. Remaining issues are:

 - broken on node v0.10.x (unrelated to this PR)
 - Compile with g++ 6 is not working because the `mapnik-config` is bringing in `-Wc++14-extensions` because the mason binaries were create dwith clang. Going to try removing this to workaround https://github.com/mapnik/mapnik/pull/3778. Alt approach will be to avoid saving this clang-specific flag into `mapnik-config`.

**Comment by springmeyer** [comment]
@artemp - can you comment on the status of windows support? Also, can you update the mason package to bring in the fix from https://github.com/mapnik/mapnik/pull/3778?

**Comment by artemp** [comment]
@springmeyer - windows support is not present because mapnik master (aka 3.1.x) has (had?) issues with c++14 support in VS.

**Pull request merged**
