### PR TITLE
rebundle `node-pre-gyp` and do not preinstall it

### LINKED ISSUE #650: you cannot run "npm install" inside of preinstall. this creates an install loop in npm 3+
because of this: https://github.com/mapnik/node-mapnik/commit/df7d542885781a7949fef4dccc030a71f8d8c985

You cannot run `npm install` anything inside of the `preinstall`, because `npm install` runs `preinstall`.
This is pointless, anyway, because `node-pre-gyp` is a dependency already.

This happens:
```
$ npm install mapnik
(node:34121) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
fetchMetadata → network   ▌ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> mapnik@3.5.13 preinstall /Users/tjwebb/workspace/langa/underbuilt/api-server/node_modules/.staging/mapnik-d6304832
> npm install node-pre-gyp

(node:34209) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> mapnik@3.5.13 preinstall /Users/tjwebb/workspace/langa/underbuilt/api-server/node_modules/.staging/mapnik-d6304832/node_modules/.staging/mapnik-5b75902b
> npm install node-pre-gyp

(node:34265) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> mapnik@3.5.13 preinstall /Users/tjwebb/workspace/langa/underbuilt/api-server/node_modules/.staging/mapnik-d6304832/node_modules/.staging/mapnik-5b75902b/node_modules/.staging/mapnik-3e3892ff
> npm install node-pre-gyp
```

and so on, forever, until eventually it looks like this:

```
/Users/tjwebb/workspace/langa/underbuilt/api-server/node_modules/.staging/mapnik-d6304832/node_modules/.staging/mapnik-5b75902b/node_modules/.staging/mapnik-3e3892ff/node_modules/.staging/mapnik-6a353413/node_modules/.staging/mapnik-872c850e/node_modules/.staging/mapnik-8edd7495/node_modules/.staging/mapnik-ada28736/node_modules/.staging/mapnik-aa3f2198/node_modules/.staging/mapnik-129f704a/node_modules/.staging/mapnik-9e1cde87/node_modules/.staging/mapnik-89279f14/node_modules/.staging/mapnik-7b7084a4/npm-debug.log
```

etc.

### PR DESCRIPTION
**Pull request by Mithgol**
Partially reverts df7d542885781a7949fef4dccc030a71f8d8c985 to prevent an endless loop in npm v3.

Fixes #650, #640, #630.

### CODE REVIEW

**Comment by Mithgol** [comment]
Some tests failed on Travis CI for the reasons that do not seem related.

**Comment by BHare1985** [comment]
Can this be revisited and given some sort of priority? Seems a good majority of issues being made are related to this. I am sure there are a lot more people who are having issues and just not reporting them as well.

@springmeyer

**Comment by springmeyer** [comment]
my opinion: https://github.com/mapnik/node-mapnik/issues/650#issuecomment-229747309

**Comment by Mithgol** [comment]
Okay.

However, if this issue is seen as a problem in npm, someone should report it to npm.

**Comment by springmeyer** [comment]
> However, if this issue is seen as a problem in npm, someone should report it to npm.

It is https://github.com/npm/npm/issues/12583

**Comment by tjwebb** [comment]
This is not a bug in npm, it's a misunderstanding of how npm is supposed to work. There's no reason the install command should `npm install` something. That's what the f*cking `dependencies` list is for.

**Pull request closed without merging**
