### PR TITLE
Persist buffer in internal field when using zero-copy fromBufferSync

### LINKED ISSUE #580: Persist underlying buffer for mapnik.Image.fromBufferSync
Let's add a `Nan::Persistent` ref to preserve the underlying pixel data buffer when creating an image with `mapnik.Image.fromBufferSync`. This would keep this method zero-copy while minimizing the dependency on the lifetime of an external object and allow us to [remove the current scary warning recommending to not use this method](https://github.com/mapnik/node-mapnik/blob/03b3eb086eed36f68d483201db905a15f8a2f058/src/mapnik_image.cpp#L2782-L2783).

I'm not too familiar with the low level bits here, but from reading a little it sounds like we can't `std::move` the underlying `char*` from the buffer. It looks like node-osmium achieves similar functionality here by [wrapping the buffer, then moving the wrapper](https://github.com/osmcode/node-osmium/blob/93480131a1458c5cda44c0a6a8886f8cd3ee5687/src/buffer_wrap.cpp#L47)? I suppose an implementation like this could be an alternative to keeping an external buffer alive.

### PR DESCRIPTION
**Pull request by mikemorris**
Fixes #580 

/cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
Before merging this I'd like to manually test. While I'm sure it is correct the `lcons->InstanceTemplate()->SetInternalFieldCount(2);` is freaky. I want to do some manual tests with `node-wek` to make sure things still get garbage collected.

**Comment by mikemorris** [comment]
It's not that freaky! :stuck_out_tongue_winking_eye:

**Comment by mikemorris** [comment]
Hrm, so failing tests here look like the buffer may not be persisted correctly...

**Comment by springmeyer** [comment]
Closing, fixed in #677

**Pull request closed without merging**
